services:
  postgres_pgvector:
    image: pgvector/pgvector:pg17
    container_name: aria_pgvector
    ports:
      - "6024:5432"
    environment:
      POSTGRES_USER: aria_user
      POSTGRES_PASSWORD: aria_password
      POSTGRES_DB: aria_db
    networks:
      - aria_network
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/pg-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./scripts/pg-config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aria_user -d aria_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  data-access-service:
    build: ../backend-fastapi/data-access-service
    container_name: data-access-service
    ports:
      - "8004:8000"
    depends_on:
      - postgres_pgvector
    networks:
      - aria_network

  data-ingestion-service:
    build: ../backend-fastapi/data-ingestion-service
    container_name: data-ingestion-service
    ports:
      - "8002:8000"
    networks:
      - aria_network
    depends_on:
      - postgres_pgvector
      - embedding-service
      - data-access-service
  
  embedding-service:
    build: ../backend-fastapi/embedding-service
    container_name: embedding-service
    ports:
      - "8001:8000"
    networks:
      - aria_network

  rewards-query-service:
    build: ../backend-fastapi/rewards-query-service
    container_name: rewards-query-service
    ports:
      - "8003:8000"
    networks:
      - aria_network

volumes:
  pgvector_data:

networks:
  aria_network: