services:
  postgres_pgvector:
    image: pgvector/pgvector:pg17
    container_name: aria_pgvector
    environment:
      POSTGRES_USER: aria_user
      POSTGRES_PASSWORD: aria_password
      POSTGRES_DB: aria_db
    ports:
      - "6024:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/pg-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./scripts/pg-config/postgresql.conf:/etc/postgresql/postgresql.conf

    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aria_user -d aria_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data: